nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.org"
  whitebeardit:
    npmAuthToken: "${GITHUB_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
